# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170321_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_add_ul', models.CharField(max_length=100)),
                ('cl_add_nrd', models.CharField(max_length=20)),
                ('cl_add_nrm', models.CharField(max_length=20)),
                ('cl_ip', models.GenericIPAddressField()),
                ('last_log_seen', models.CharField(max_length=100)),
                ('speed', models.ForeignKey(db_column='Speed_packet_ID', on_delete=django.db.models.deletion.CASCADE, to='clients.Speed_packet')),
                ('srv', models.ForeignKey(db_column='Client_service_ID', on_delete=django.db.models.deletion.CASCADE, to='clients.Client_service')),
            ],
        ),
    ]
